spring:
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace

multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/master_db?useSSL=false
        username: root
        password:
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
